### ISSUE TITLE
Error calling 'determine_network_location'

### ISSUE THREAD

**Issue by FooBarQuaxx** [xolox/python-dwim#1]
Hi there.

I tried to follow the documentation to create a basic ~/.dwimrc file. I got this error when running the executable just by calling 'determine_network_location' on the profile file : 
```
4480 Code/python-dwim git:(master) ✗ » dwim
2017-05-02 18:50:52 med-worksation dwim[26203] INFO Initializing dwim 0.2 ..
2017-05-02 18:50:52 med-worksation dwim[26203] INFO Loading /home/med/.dwimrc ..
2017-05-02 18:50:52 med-worksation dwim[26203] ERROR Caught a fatal exception! Terminating ..
Traceback (most recent call last):
  File "/home/med/Code/python-dwim/dwim/__init__.py", line 69, in main
    execfile(filename, environment, environment)
  File "/home/med/.dwimrc", line 1, in <module>
    location = determine_network_location(home=['AA:BB:CC:DD:EE:FF'])
NameError: name 'determine_network_location' is not defined
```

Note that I installed dwim from a checkout of the source code.

**Comment by xolox** [comment]
Thanks for the feedback! I just published version 0.3 which should fix the problem, so I'm going to close this issue now. If the problem persists for you then please feel free to reopen this issue or open a new one.
